import { productSystemAssets } from "@/lib/products/product-assets";
import type { ProductSystem } from "@/lib/products/en-product-systems";

export const faProductSystems: readonly ProductSystem[] = [
  {
    id: "water",
    number: "01",
    name: "آب",
    slug: "water-supply-pipe",
    path: "/products/water-supply-pipe",
    image: productSystemAssets.water,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#33aaff",
    accentMuted: "rgba(51, 170, 255, 0.12)",
    icon: "water",
    eyebrow: "سیستم‌های لوله آبرسانی",
    title: "جریان مطمئن. هر قطره.",
    description:
      "لوله HDPE آبرسانی برای انتقال شهری، روستایی و صنعتی — باطن صاف، مناسب جوش و بدون خوردگی در خاک.",
    tags: ["PE100", "سیستم‌های فشار", "شهری / صنعتی"],
    specs: [
      { label: "کاربرد", value: "شبکه آب شرب و خام" },
      { label: "اتصال", value: "سازگار با جوش butt fusion" },
      { label: "تولید", value: "خطوط واجد INSO 14427-2" },
      { label: "سطح", value: "باطن داخلی صاف" },
      { label: "خدمت", value: "مدفون بدون خوردگی" },
    ],
    ctaLabel: "مشاهده لوله آبرسانی",
    imageAlt: "لوله HDPE آبرسانی با نوار آبی در محیط انتقال آب",
  },
  {
    id: "gas",
    number: "02",
    name: "گاز",
    slug: "gas-pipe",
    path: "/products/gas-pipe",
    image: productSystemAssets.gas,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#e8b923",
    accentMuted: "rgba(232, 185, 35, 0.12)",
    icon: "gas",
    eyebrow: "سیستم‌های لوله گاز",
    title: "یکپارچگی توزیع زیرزمینی.",
    description:
      "لوله پلی‌اتیلن تک‌جداره برای انشعاب و توزیع گاز — مقاوم در برابر خوردگی و مناسب اتصالات جوشی.",
    tags: ["PE100", "الکتروفیوژن", "شبکه توزیع"],
    specs: [
      { label: "کاربرد", value: "انشعاب و توزیع گاز" },
      { label: "اتصال", value: "الکتروفیوژن در صورت تعیین" },
      { label: "محیط", value: "خاک و زیرساخت" },
      { label: "انعطاف", value: "مسیرهای منحنی" },
      { label: "مرجع", value: "بر اساس مشخصات پروژه" },
    ],
    ctaLabel: "مشاهده لوله گاز",
    imageAlt: "لوله HDPE گاز با نوار کهربایی در بستر زیرساخت",
  },
  {
    id: "irrigation",
    number: "03",
    name: "آبیاری",
    slug: "irrigation-pipe",
    path: "/products/irrigation-pipe",
    image: productSystemAssets.irrigation,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#3ecf7a",
    accentMuted: "rgba(62, 207, 122, 0.12)",
    icon: "irrigation",
    eyebrow: "سیستم‌های لوله آبیاری",
    title: "خطوط فشار آماده مزرعه.",
    description:
      "لوله پلی‌اتیلن برای خطوط فشار آبیاری کشاورزی بین منبع، مخزن و شبکه مزرعه.",
    tags: ["خطوط فشار", "کشاورزی", "سازگار با جوش"],
    specs: [
      { label: "کاربرد", value: "خطوط تغذیه مزرعه" },
      { label: "زمینه", value: "از پمپ تا هدر مزرعه" },
      { label: "مسیر", value: "زمین ناهموار" },
      { label: "شبکه", value: "تغذیه قطره‌ای و بارانی" },
      { label: "دوام", value: "شیمی آب آبیاری" },
    ],
    ctaLabel: "مشاهده لوله آبیاری",
    imageAlt: "لوله HDPE آبیاری با نوار سبز در مزرعه",
  },
  {
    id: "sewer",
    number: "04",
    name: "فاضلاب",
    slug: "sewage-pipe",
    path: "/products/sewage-pipe",
    image: productSystemAssets.sewer,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#a56bff",
    accentMuted: "rgba(165, 107, 255, 0.12)",
    icon: "sewer",
    eyebrow: "سیستم‌های لوله فاضلاب",
    title: "جمع‌آوری فاضلاب زیر سطح.",
    description:
      "لوله پلی‌اتیلن برای جمع‌آوری فاضلاب شهری و صنعتی — مقاومت شیمیایی و یکپارچگی اتصال جوشی.",
    tags: ["فاضلاب بهداشتی", "اتصالات جوشی", "شبکه مدفون"],
    specs: [
      { label: "کاربرد", value: "جمع‌آوری فاضلاب" },
      { label: "محیط", value: "عملکرد در خاک مرطوب" },
      { label: "شیمی", value: "مقاومت فاضلاب رایج" },
      { label: "نصب", value: "کارهای سبک عمرانی" },
      { label: "طراحی", value: "شیب طبق مشخصات" },
    ],
    ctaLabel: "مشاهده لوله فاضلاب",
    imageAlt: "لوله HDPE فاضلاب با accent بنفش در تونل زیرزمینی",
  },
  {
    id: "drainage",
    number: "05",
    name: "زهکشی",
    slug: "drainage-pipe",
    path: "/products/drainage-pipe",
    image: productSystemAssets.drainage,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#2ec4d6",
    accentMuted: "rgba(46, 196, 214, 0.12)",
    icon: "drainage",
    eyebrow: "سیستم‌های لوله زهکشی",
    title: "آب سطحی، جریان کنترل‌شده.",
    description:
      "لوله پلی‌اتیلن برای زهکشی سطحی و زیرسطحی — هدایت آب باران، نه فاضلاب بهداشتی.",
    tags: ["آب باران", "زهکشی سطحی", "شبکه عمرانی"],
    specs: [
      { label: "کاربرد", value: "زهکشی سطحی و سایت" },
      { label: "هیدرولیک", value: "ظرفیت باطن صاف" },
      { label: "زمینه", value: "پروژه‌های راه و حیاط" },
      { label: "مسیر", value: "مسیریابی انعطاف‌پذیر" },
      { label: "طراحی", value: "بر اساس شیب هیدرولیک" },
    ],
    ctaLabel: "مشاهده لوله زهکشی",
    imageAlt: "لوله HDPE زهکشی با نوار فیروزه‌ای در محیط آب باران",
  },
  {
    id: "pe100",
    number: "06",
    name: "PE100",
    slug: "pe100-pipe",
    path: "/products/pe100-pipe",
    image: productSystemAssets.pe100,
    imageWidth: 1672,
    imageHeight: 941,
    accent: "#33aaff",
    accentMuted: "rgba(51, 170, 255, 0.12)",
    icon: "pe100",
    eyebrow: "گرید ماده PE100",
    title: "MRS بالاتر. طراحی فشار سنگین.",
    description:
      "لوله پلی‌اتیلن PE100 با MRS بالاتر برای طراحی فشار بیشتر — دیواره نازک‌تر یا کلاس بالاتر در همان SDR.",
    tags: ["گرید PE100", "طراحی فشار", "مشخصات مهندسی"],
    specs: [
      { label: "ماده", value: "گرید MRS — PE100" },
      { label: "طراحی", value: "بخش‌های فشار بالاتر" },
      { label: "کاربرد", value: "انتقال صنعتی" },
      { label: "مهندسی", value: "PN / SDR طبق پروژه" },
      { label: "QC", value: "دامنه مکانیکی آزمایشگاه" },
    ],
    ctaLabel: "مشاهده PE100",
    imageAlt: "برش مهندسی لوله PE100 HDPE در محیط فنی آبی",
  },
] as const;
